"use client";

import { motion } from "framer-motion";

function Section({num,title,kicker,children}:{num:string;title:string;kicker:string;children:React.ReactNode}){
  return <section className="border-t border-cream-100/[.07] px-6 py-24 md:px-12 lg:px-20 xl:px-28"><div className="mx-auto max-w-6xl"><div className="mb-12 flex gap-5"><span className="font-mono text-[10px] tracking-[.2em] text-signal-500">{num}</span><div><h2 className="font-display text-5xl text-cream-50 md:text-6xl">{title}</h2><p className="mt-4 max-w-2xl text-sm leading-7 text-cream-500">{kicker}</p></div></div>{children}</div></section>
}

function SpatialPlan(){
 return <div className="overflow-hidden rounded-[28px] border border-cream-100/10 bg-[#0b1020] p-4 shadow-2xl md:p-6">
   <div className="overflow-hidden rounded-[22px] border border-cream-100/10 bg-[#11182a]"><img src="/media/tnfd-floorplan.webp" alt="Proposed TNFD workshop floor plan" className="block h-auto w-full object-contain" /></div>
   <div className="flex flex-wrap gap-x-8 gap-y-2 px-2 pt-4 text-[9px] uppercase tracking-[.16em] text-cream-500"><span><b className="text-depth-300">14 round tables</b> · 5 chairs each · 5–4–5 arrangement</span><span><b className="text-signal-500">10 VIP armchairs</b> · 2.00 m stage clearance</span><span><b className="text-depth-300">6 column speakers</b> · 3 left / 3 right</span></div>
 </div>
}

export default function TNFD(){
 return <main className="min-h-screen bg-[#050813] text-cream-100">
   <div className="fixed left-6 top-6 z-[60] md:left-8 md:top-7"><img src="/brand/paradigm-white.png" alt="Paradigm Capital Group" className="h-auto w-[96px] object-contain md:w-[108px]" /></div>
   <aside className="fixed left-0 top-0 z-40 hidden h-screen w-[220px] border-r border-cream-100/[.07] bg-[#050813]/85 px-7 py-8 backdrop-blur-xl xl:block"><div className="pt-36 text-[9px] uppercase tracking-[.2em] text-cream-500">Paradigm Events</div><div className="mt-3 font-display text-2xl leading-[.95] text-cream-50">TNFD<br/>Technical Proposal</div><div className="mt-9 space-y-4 text-[10px] uppercase tracking-[.12em] text-cream-500"><div>01 · Brief</div><div className="text-signal-500">02 · Spatial Concept</div><div>03 · Technical Production</div><div>04 · Interpretation</div><div>05 · VIP Experience</div><div>06 · Guest Experience</div><div>07 · TOR Coverage</div></div><div className="absolute bottom-8 text-[9px] uppercase tracking-[.14em] leading-5 text-cream-500">08 September 2026<br/>Dusit Thani Lakeview<br/>New Cairo · Egypt</div></aside>

   <section className="relative flex min-h-screen items-center overflow-hidden px-6 py-24 xl:pl-[280px] xl:pr-24"><div className="absolute inset-0 bg-[radial-gradient(circle_at_70%_35%,rgba(46,119,135,.2),transparent_38%),linear-gradient(180deg,#080d1c,#04060d)]"/><div className="relative mx-auto w-full max-w-6xl"><div className="eyebrow text-depth-300">TNFD WORKSHOP · 08 SEPTEMBER 2026</div><motion.h1 initial={{opacity:0,y:30}} animate={{opacity:1,y:0}} transition={{duration:1}} className="mt-8 max-w-5xl font-display text-7xl leading-[.92] text-cream-50 md:text-9xl">TNFD<br/><span className="text-depth-100">Workshop</span></motion.h1><p className="mt-8 max-w-2xl font-display text-2xl text-signal-500">Technical & Spatial Proposal</p><p className="mt-8 max-w-xl text-[15px] leading-7 text-cream-300/70">A premium workshop environment designed around clear sightlines, balanced technical coverage, executive comfort and a controlled interpretation workflow.</p><div className="mt-14 grid max-w-3xl grid-cols-2 gap-8 border-t border-cream-100/10 pt-7 md:grid-cols-5"><div><b className="font-display text-3xl text-signal-500">75</b><small className="mt-1 block text-[9px] uppercase tracking-[.15em] text-cream-500">Participants</small></div><div><b className="font-display text-3xl text-signal-500">14</b><small className="mt-1 block text-[9px] uppercase tracking-[.15em] text-cream-500">Round tables</small></div><div><b className="font-display text-3xl text-signal-500">10</b><small className="mt-1 block text-[9px] uppercase tracking-[.15em] text-cream-500">VIP armchairs</small></div><div><b className="font-display text-3xl text-signal-500">6</b><small className="mt-1 block text-[9px] uppercase tracking-[.15em] text-cream-500">Column speakers</small></div><div><b className="font-display text-3xl text-signal-500">1</b><small className="mt-1 block text-[9px] uppercase tracking-[.15em] text-cream-500">Dusit Thani Lakeview</small></div></div></div></section>

   <Section num="01" title="The Brief" kicker="The room is treated as one integrated production environment — not a collection of separate rental items."><div className="grid gap-6 md:grid-cols-3"><div className="rounded-2xl border border-cream-100/10 bg-[#0a1020] p-7"><div className="eyebrow text-depth-300">Venue</div><h3 className="mt-4 font-display text-3xl text-cream-50">Dusit Thani Lakeview</h3><p className="mt-3 text-sm leading-6 text-cream-500">New Cairo, Egypt · private luxury hotel setting.</p></div><div className="rounded-2xl border border-cream-100/10 bg-[#0a1020] p-7"><div className="eyebrow text-depth-300">Format</div><h3 className="mt-4 font-display text-3xl text-cream-50">75 Participants</h3><p className="mt-3 text-sm leading-6 text-cream-500">08:00–18:00 workshop format with executive and technical support.</p></div><div className="rounded-2xl border border-cream-100/10 bg-[#0a1020] p-7"><div className="eyebrow text-depth-300">Presentation</div><h3 className="mt-4 font-display text-3xl text-cream-50">10 × 3 m Stage</h3><p className="mt-3 text-sm leading-6 text-cream-500">8 × 3 m LED screen with podium and presentation support.</p></div></div></Section>

   <Section num="02" title="Spatial Concept" kicker="A balanced 5–4–5 table rhythm, a straight VIP line, rear technical control, isolated interpretation and six evenly distributed column speakers."><SpatialPlan/></Section>

   <Section num="03" title="Technical Production" kicker="The technical layer remains clean and discreet while maintaining reliable coverage throughout the room."><div className="grid gap-5 md:grid-cols-2"><div className="rounded-2xl border border-cream-100/10 bg-[#0a1020] p-8"><div className="eyebrow text-signal-500">Audio</div><h3 className="mt-4 font-display text-4xl text-cream-50">6 Column Speakers</h3><p className="mt-4 text-sm leading-7 text-cream-500">Three on the left and three on the right, positioned for balanced room coverage without crowding the stage edge. Two additional monitor speakers face the presenters.</p></div><div className="rounded-2xl border border-cream-100/10 bg-[#0a1020] p-8"><div className="eyebrow text-signal-500">AV / Hybrid</div><h3 className="mt-4 font-display text-4xl text-cream-50">Presentation Ready</h3><p className="mt-4 text-sm leading-7 text-cream-500">6 wireless microphones, 8 × 3 m LED, projector and white screen, Zoom-ready hybrid setup and 90 Mbps dedicated internet.</p></div><div className="rounded-2xl border border-cream-100/10 bg-[#0a1020] p-8"><div className="eyebrow text-signal-500">Stage</div><h3 className="mt-4 font-display text-4xl text-cream-50">10 × 3 m</h3><p className="mt-4 text-sm leading-7 text-cream-500">10 VIP armchairs remain separated from the stage with a minimum 2 m clearance.</p></div><div className="rounded-2xl border border-cream-100/10 bg-[#0a1020] p-8"><div className="eyebrow text-signal-500">Control</div><h3 className="mt-4 font-display text-4xl text-cream-50">Centralized Unit</h3><p className="mt-4 text-sm leading-7 text-cream-500">Rear control position supporting show playback, audio routing, stage monitoring and hybrid coordination.</p></div></div></Section>

   <Section num="04" title="Interpretation" kicker="A dedicated interpretation workflow keeps the language layer isolated while remaining fully connected to the room."><div className="grid gap-5 md:grid-cols-2"><div className="rounded-2xl border border-cream-100/10 bg-[#0a1020] p-8"><div className="eyebrow text-depth-300">Interpretation Booth</div><h3 className="mt-4 font-display text-4xl text-cream-50">English ↔ Arabic</h3><p className="mt-4 text-sm leading-7 text-cream-500">Dedicated booth at the rear-left, with simultaneous interpretation and 75 wireless listening headphones.</p></div><div className="rounded-2xl border border-cream-100/10 bg-[#0a1020] p-8"><div className="eyebrow text-depth-300">Control Unit</div><h3 className="mt-4 font-display text-4xl text-cream-50">Central Show Control</h3><p className="mt-4 text-sm leading-7 text-cream-500">Positioned at the rear center to keep the production workflow controlled and visually discreet.</p></div></div></Section>

   <Section num="05" title="VIP Experience" kicker="A dedicated front-row experience gives distinguished guests clear sightlines while preserving the working-table layout behind them."><div className="rounded-[28px] border border-signal-500/25 bg-gradient-to-r from-[#11192b] to-[#0a1020] p-10"><div className="grid gap-8 md:grid-cols-3"><div><div className="font-display text-5xl text-signal-500">10</div><div className="mt-2 text-xs uppercase tracking-[.16em] text-cream-500">Armchairs</div></div><div><div className="font-display text-5xl text-signal-500">2 m</div><div className="mt-2 text-xs uppercase tracking-[.16em] text-cream-500">Clearance from stage</div></div><div><div className="font-display text-5xl text-signal-500">5–4–5</div><div className="mt-2 text-xs uppercase tracking-[.16em] text-cream-500">Table rhythm</div></div></div></div></Section>

   <Section num="06" title="Guest Experience" kicker="A discreet production footprint supports a polished participant experience from arrival through close."><div className="grid gap-5 md:grid-cols-3"><div className="rounded-2xl border border-cream-100/10 bg-[#0a1020] p-7"><div className="eyebrow text-depth-300">Registration</div><h3 className="mt-4 font-display text-3xl text-cream-50">Arrival Ready</h3><p className="mt-3 text-sm leading-6 text-cream-500">Registration support, wireless printer and branded participant materials.</p></div><div className="rounded-2xl border border-cream-100/10 bg-[#0a1020] p-7"><div className="eyebrow text-depth-300">Hospitality</div><h3 className="mt-4 font-display text-3xl text-cream-50">Continuous Service</h3><p className="mt-3 text-sm leading-6 text-cream-500">Coffee breaks, lunch and continuous refreshments coordinated around the programme.</p></div><div className="rounded-2xl border border-cream-100/10 bg-[#0a1020] p-7"><div className="eyebrow text-depth-300">VIP</div><h3 className="mt-4 font-display text-3xl text-cream-50">Dedicated Care</h3><p className="mt-3 text-sm leading-6 text-cream-500">Dedicated VIP room, lunch and front-of-room seating experience.</p></div></div></Section>

   <Section num="07" title="TOR Coverage" kicker="The proposed setup translates the requested event requirements into one coordinated technical and spatial solution."><div className="overflow-hidden rounded-2xl border border-cream-100/10"><div className="grid grid-cols-[1fr_auto] border-b border-cream-100/10 bg-[#0a1020] px-6 py-4 text-[10px] uppercase tracking-[.14em] text-cream-500"><span>Requirement</span><span>Coverage</span></div>{[["Venue & room","Dusit Thani Lakeview · New Cairo · 75 participants"],["Stage & LED","10 × 3 m stage · 8 × 3 m LED"],["Audio","6 column speakers · 2 stage monitors · 6 wireless microphones"],["Hybrid","Zoom-ready setup · 90 Mbps internet"],["Interpretation","English ↔ Arabic · booth · 75 wireless headphones"],["Seating","14 round tables × 5 chairs · 10 VIP armchairs"],["Hospitality & VIP","Coffee breaks · buffet lunch · VIP room & lunch"]].map(([a,b])=><div key={a} className="grid grid-cols-[1fr_auto] gap-6 border-t border-cream-100/10 px-6 py-5 text-sm"><span className="text-cream-200">{a}</span><span className="max-w-xl text-right text-cream-500">{b}</span></div>)}</div></Section>

   <footer className="border-t border-cream-100/[.07] px-6 py-20 xl:pl-[280px]"><div className="mx-auto max-w-6xl"><div className="font-display text-4xl text-cream-50">PARADIGM</div><p className="mt-3 text-sm text-cream-500">TNFD Workshop · Technical & Spatial Proposal</p><p className="mt-1 text-xs text-cream-600">08 September 2026 · Dusit Thani Lakeview · New Cairo, Egypt</p></div></footer>
 </main>
}
